name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: ✅ PR checks
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🎛️ Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 22

      - name: 📥 Install deps
        run: npm ci

      - name: 🔬 Lint
        run: npm run lint:check

      - name: 🧮 Format
        run: npm run format:check

      - name: 🔎 Typecheck
        run: npm run typecheck

      - name: 🔬 Test
        run: npm run test

      - name: 🏗️ Build library
        run: npm run build

      - name: 🔬 Verify build
        run: npm run build:verify
